# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: oa-bot
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
  - id: win
    env:
      - CGO_ENABLED=0
    goos:
      - windows

archives:
  - id: win
    builds:
      - win
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: binary
    replacements:
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

  - id: allOS
    builds:
      - win
      - linux
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
